<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1FKFP5A" failures="1" tests="2" name="test" time="0.565" errors="0" timestamp="26 Apr 2020 15:08:38 GMT">
  <testcase classname="testnddemo" name="m1" time="0.017">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at testnddemo.m1(testnddemo.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- m1 -->
  <testcase classname="testnddemo" name="m2" time="0.002"/>
</testsuite> <!-- test -->
